name: Hexlet CI
on: push
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - uses: actions/setup-node@v3
                          with:
                                  node-version: 16
                                  cache: 'npm'
                        - name: Linting
                          run: make lint
                        - name: Snyk check
                          uses: snyk/actions/node@master
                          env:
                                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                        - name: Code coverage
                          uses: paambaati/codeclimate-action@v3.0.0
                          env:
                                  CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_SECRET }}
                          with:
                                  coverageCommand: make test-coverage
                                  debug: true
